# Generated by Django 4.0.3 on 2022-03-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questiions',
            table='questions',
        ),
    ]
