# Generated by Django 4.0.3 on 2022-03-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_list', '0003_rename_questiions_questions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table=None,
        ),
    ]
