# Generated by Django 4.0.3 on 2022-03-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_list', '0004_alter_questions_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
    ]
