# Generated by Django 4.0.3 on 2022-03-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_list', '0006_rename_answers_answersmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionsmodel',
            table=None,
        ),
    ]
