# Generated by Django 4.0.3 on 2022-03-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_list', '0007_alter_questionsmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionsmodel',
            table='trtrtr',
        ),
    ]
